import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black w-full flex flex-col justify-center items-center">
        {children}
      </body>
    </html>
  )
}
